### ISSUE TITLE
Title in ap-taxo-meta overridden 

### ISSUE THREAD

**Issue by rachelwhitton** [anspress/categories-for-anspress#5]
Title in `ap-taxo-meta` class is not displayed. 
![screen shot 2015-11-09 at 4 45 19 pm](https://cloud.githubusercontent.com/assets/10119525/11049068/5044b5be-8701-11e5-8a74-56cb7b2e6815.png)
**Follow Question** is displayed instead of the intended `Subscribe to '. $category->name .'`

**Comment by rahularyan** [comment]
Oh, sorry for late response. Actually we do not track GitHub issue all the time. Will fix it.

**Comment by rahularyan** [comment]
I just checked this issue and found that this has been fixed already so closing the issue.
